/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-10-11 02:37:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"searchBar\" class=\"row-fluid\">\r\n");
      out.write("\t\t  \t<div class=\"span9\">\r\n");
      out.write("\t\t\t\t<div class=\"input-append\">\t\t\t\t\t\r\n");
      out.write("\t\t       \t\t<input type=\"search\" id=\"search\" placeholder=\"Buscar reclamos o usuarios...\" />\r\n");
      out.write("\t\t\t        <button id=\"btnSearch\" class='btn add-on' style=\"width:70px;\">\r\n");
      out.write("\t\t\t            <i class=\"icon-search\"></i>\r\n");
      out.write("\t\t\t        </button>\t\t\t        \r\n");
      out.write("\t\t\t        <button id=\"btnAdvancedSearch\" class='btn add-on'>\r\n");
      out.write("\t\t\t            <i class=\"icon-angle-down\"></i>\r\n");
      out.write("\t\t\t        </button>  \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t<div class=\"span3\">\t\r\n");
      out.write("\t\t\t\t<button id=\"btnIssue\" class=\"btn btn-warning\"  data-toggle=\"button\"> \r\n");
      out.write("\t\t\t\t\t<i class=\"icon-map-marker icon-large\"></i>&nbsp;&nbsp;&nbsp;NUEVO RECLAMO\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- ROW 1 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"container\" style=\"margin:0;padding:0;height:450px\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t  <!-- MAP -->  \t \t\t\t\t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t\t\t<select id=\"cbxProvincias\" name=\"cbxProvincias\" onchange=\"findProvincia(value);return false\" onfocus=\"\">              \t\r\n");
      out.write("\t\t\t\t\t<option value=\"BA\">Buenos Aires</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"CF\">Capital Federal</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"CT\">Catamarca</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"CC\">Chaco</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"CH\">Chubut</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"CD\">Córdoba</option>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"CR\">Corrientes</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"ER\">Entre Ríos</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"FO\">Formosa</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"JY\">Jujuy</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"LP\">La Pampa</option>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"LR\">La Rioja</option>\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"MZ\">Mendoza</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"MN\">Misiones</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"NQ\">Neuquén</option>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"RN\">Río Negro</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"SA\">Salta</option>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"SJ\">San Juan</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"SL\">San Luis</option>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"SC\">Santa Cruz</option>\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"SF\">Santa Fe</option>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"SE\">Santiago del Estero</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"TF\">Tierra del Fuego</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"TM\">Tucumán</option>\t\t\t\t\t\r\n");
      out.write("\t\t  \t\t</select>\r\n");
      out.write("\t\t  \t\t\r\n");
      out.write("\t\t  \t\t<div id=\"map_canvas\"></div>\t\t  \r\n");
      out.write("\t\r\n");
      out.write("\t\t  <!-- ISSUE FORM -->\r\n");
      out.write("\t\t\t\t<form id=\"issueForm\" class=\"form-issue\" method=\"POST\">\t\r\n");
      out.write("\t\t\t\t\t <div id=\"issueHeader\" class=\"page-header \">\r\n");
      out.write("    \t \t\t\t\t<h4>Carg&aacute; tu reclamo</h4>    \t \t\r\n");
      out.write("    \t\t\t\t </div>  \t\t\t\t \r\n");
      out.write("\t\t\t\t\t <div id=\"fieldWrapper\">\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \t\t<!-- STEP 1 -->\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset id=\"issueStep1\" class=\"step\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"latitude\" name=\"latitude\"  />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"longitude\" name=\"longitude\" />\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"address\" name=\"address\" placeholder=\"Dirección (calle y altura)\" />\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"neighborhood\" name=\"neighborhood\" placeholder=\"Barrio (opcional)\"/>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"city\" name=\"city\" placeholder=\"Ciudad\" />\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"province\" name=\"province\" placeholder=\"Provincia\"/>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- STEP 2 -->\r\n");
      out.write("\t\t\t\t\t\t \t<fieldset id=\"issueStep2\" class=\"step\">\r\n");
      out.write("\t\t\t\t\t\t \t\t<input type=\"text\" id=\"title\" name=\"title\" placeholder=\"T&iacute;tulo\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea rows=\"5\" id=\"description\" name=\"description\" placeholder=\"Descripci&oacute;n...\"></textarea>\t\t\r\n");
      out.write("\t\t\t\t\t\t \t</fieldset>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- STEP 3 -->\r\n");
      out.write("\t\t\t\t\t\t  \t<fieldset id=\"issueStep3\" class=\"step\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fileupload fileupload-new\" data-provides=\"fileupload\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fileupload-new thumbnail\" style=\"width: 304px; height: 150px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fileupload-preview fileupload-exists thumbnail\" style=\"height: 150px;min-width:300px;max-width: 200px; max-height: 150px; line-height: 20px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"btn btn-file\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"fileupload-new\"><i class=\"icon-plus\"></i>&nbsp;&nbsp;Seleccionar imagen</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"fileupload-exists\"><i class=\"icon-refresh\"></i>&nbsp;&nbsp;Cambiar</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn fileupload-exists\" data-dismiss=\"fileupload\"><i class=\"icon-trash\"></i>&nbsp;&nbsp; Quitar</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"eventTags\"></ul>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"demoNavigation\"> \r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"btn btn-primary\" id=\"btnBackNext\" type=\"reset\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"btn btn-primary\" id=\"btnIssueSubmit\" type=\"submit\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</form>\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\r\n");
      out.write("<!-- \t<div id=\"alert_placeholder\" style=\"height:50px;display:none\"></div>\t -->\r\n");
      out.write("\t<!-- ROW 2 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--Sidebar content-->\r\n");
      out.write("\t\t<div class=\"row-fluid\" style=\"height:auto;margin-top:30px;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <div class=\"span3\">\r\n");
      out.write("\t\t\t<div class=\"page-header\">\r\n");
      out.write("    \t   \t\t<h4><i class=\"icon-user icon-large\"></i>&nbsp;&nbsp;Usuarios más activos</h4>    \t \t\r\n");
      out.write("    \t   </div>    \r\n");
      out.write("\t\t      \r\n");
      out.write("\t      \t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"border-top:none\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t  <a class=\"pull-left thumbnail\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t    <img class=\"media-object\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/images/nopic64.png\">\r\n");
      out.write("\t\t\t\t\t\t  </a>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t    <a href=\"#\"><h5 class=\"media-heading\">ariel_xyz</h5></a>\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t    <p style=\"font-size:11px\">1101 reclamos <br>\r\n");
      out.write("\t\t\t\t\t\t    99 comentarios</p>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t \t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"border-top:1px dashed #dddddd; border-bottom:1px dashed #dddddd\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t  <a class=\"pull-left thumbnail\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t    <img class=\"media-object\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/images/nopic64.png\">\r\n");
      out.write("\t\t\t\t\t\t  </a>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t    <a href=\"#\"><h5 class=\"media-heading\">SuperUser</h5></a>\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t    <p style=\"font-size:11px\">977 reclamos <br>\r\n");
      out.write("\t\t\t\t\t\t    142 comentarios</p>\t\t\t\t\t\t\t\t\t \t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t</table>\t\t\r\n");
      out.write("\t\t\t<p style=\"text-align:center;\"><a href=\"#\" >ver más</a>\t</p>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"span4\">\r\n");
      out.write("\t\t   <div class=\"page-header\">\r\n");
      out.write("    \t   \t\t<h4><i class=\"icon-map-marker icon-large\"></i>&nbsp;&nbsp;Últimos reclamos</h4>    \t \t\r\n");
      out.write("    \t   </div>    \r\n");
      out.write("\t\t      \r\n");
      out.write("\t      \t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"border-top:none\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t  <a class=\"pull-left thumbnail\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t    <img class=\"media-object\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/images/nopic64.png\">\r\n");
      out.write("\t\t\t\t\t\t  </a>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t    <a href=\"#\"><h5 class=\"media-heading\">Ramas de árbol tapan semáforo</h5></a>\t\t\r\n");
      out.write("\t\t\t\t\t\t    <p style=\"font-size:11px\">10/06/13 en <a href=\"#\">Mendoza</a><br>\r\n");
      out.write("\t\t\t\t\t\t    Reportado por: <a href=\"#\">el_user_22</a>\r\n");
      out.write("\t\t\t\t\t\t     </p>\t\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"border-top:1px dashed #dddddd; border-bottom:1px dashed #dddddd\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t  <a class=\"pull-left thumbnail\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t    <img class=\"media-object\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/images/nopic64.png\">\r\n");
      out.write("\t\t\t\t\t\t  </a>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t    <a href=\"#\"><h5 class=\"media-heading\">Mampostería de edificio deteriorada</h5></a>\t\t\r\n");
      out.write("\t\t\t\t\t\t    <p style=\"font-size:11px\">10/06/13 en <a href=\"#\">Buenos Aires</a><br>\r\n");
      out.write("\t\t\t\t\t\t    Reportado por: <a href=\"#\">pablivo-clavo-un-clavito</a>\r\n");
      out.write("\t\t\t\t\t\t     </p>\t\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<p style=\"text-align:center;\"><a href=\"#\" >ver más</a>\t</p>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \r\n");
      out.write("     </div>\r\n");
      out.write("      \r\n");
      out.write("\t\r\n");
      out.write("\t</div><!-- /CONTENT -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
