/*  Script by Cora Reyes Calens              */ 	 				     
/*  Done for UrbanusJam!		             */						 
/*  Contact:     			                 */
/*			urbanusjam@gmail.com             */				 
/*    		coripel@gmail.com				 */	 
/*  Copyright Fixeala - 2013	             */
/*  Created:  08-10-2013 (dd-MM-YYYY)        */
/*  Modified: 08-10-2013                     */
		

DROP DATABASE IF EXISTS fixeala;
CREATE DATABASE fixeala;
USE fixeala;


/* USER */	
CREATE TABLE USER ( 
	   USERNAME VARCHAR(50) NOT NULL,
	   PASSWORD VARCHAR(50) NOT NULL,    
	   EMAIL VARCHAR(255) NOT NULL,       
	   SALT VARCHAR(25) default NULL,	
	   NEIGHBORHOOD VARCHAR (64) NULL,  
	   REGISTRATION_DATE DATETIME NULL,     
	   LAST_PASSWORD_CHANGE_DATE DATETIME NULL,    	   
	   LAST_LOGIN_DATE DATETIME NULL,   
	   CLOSED_ACCOUNT_DATE DATETIME NULL,   	           
	   ENABLED TINYINT(1) NOT NULL,		
	   
	   PRIMARY KEY(USERNAME),
	   UNIQUE KEY (EMAIL),
	   KEY (USERNAME, PASSWORD)
	   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* AUTHORITY */	
CREATE TABLE AUTHORITY (
	   USERNAME VARCHAR(50) NOT NULL,
	   AUTHORITY VARCHAR(50) NOT NULL,
		
	   PRIMARY KEY(USERNAME, AUTHORITY),
	   FOREIGN KEY (USERNAME) REFERENCES USER (USERNAME)
	   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* 	
CREATE TABLE PERMISSION (	   	  
	   ID_PERMISSION BIGINT(20) NOT NULL AUTO_INCREMENT, 
	   PERMISSION VARCHAR(50) NOT NULL,	 
		
	   PRIMARY KEY(ID_PERMISSION),
	   UNIQUE KEY(PERMISSION)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE AUTHORITY_PERMISSION (	   	  
	   ID_AUTHORITY VARCHAR(50) NOT NULL
	   ID_PERMISSION VARCHAR(50) NOT NULL,
		
	   PRIMARY KEY(PERMISSION, AUTHORITY),
	   FOREIGN KEY (ID_AUTHORITY) REFERENCES AUTHORITY (AUTHORITY),
       FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSION (ID_PERMISSION)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
*/

/* ACTIVATION */	
CREATE TABLE ACTIVATION ( 
	   TOKEN VARCHAR(126) NOT NULL,
	   USERNAME VARCHAR(50) NOT NULL,		  
	   CREATION_DATE DATETIME NOT NULL,
	   EXPIRATION_DATE DATETIME NOT NULL,
						
	   PRIMARY KEY(TOKEN),
	   UNIQUE KEY (USERNAME)
	  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* ISSUE */
CREATE TABLE ISSUE (
	   ID_ISSUE BIGINT(20) NOT NULL, 
	   USERNAME VARCHAR(50) NOT NULL,
	   REPORTED_DATE DATETIME NOT NULL,    	  
	   ADDRESS VARCHAR(255) NOT NULL,
	   NEIGHBORHOOD VARCHAR (64) NULL,  
	   CITY VARCHAR(255) NOT NULL,		
	   PROVINCE VARCHAR (64) NOT NULL,  		   
	   LATITUDE FLOAT NOT NULL,
	   LONGITUDE FLOAT NOT NULL,
	   TITLE VARCHAR(255) NOT NULL,
	   DESCRIPTION VARCHAR(500) NOT NULL,		  
	   STATUS VARCHAR(30) NOT NULL, 
	   
	   PRIMARY KEY (ID_ISSUE),
	   FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME)
	   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* TAG */
CREATE TABLE TAG (
	   ID_TAG BIGINT(20) NOT NULL AUTO_INCREMENT,
	   TAG_NAME VARCHAR (50) NOT NULL,
	   
	   PRIMARY KEY (ID_TAG)		  
	   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* ISSUE-TAG */	
CREATE TABLE ISSUE_TAG (
	   ID_ISSUE BIGINT(20) NOT NULL,
	   ID_TAG BIGINT(20) NOT NULL,		   
	   
	   PRIMARY KEY (ID_TAG, ID_ISSUE),
	   FOREIGN KEY (ID_TAG) REFERENCES TAG (ID_TAG),
	   FOREIGN KEY (ID_ISSUE) REFERENCES ISSUE (ID_ISSUE)
	   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* PASSWORD CHANGE REQUEST */
CREATE TABLE PASSWORD_CHANGE_REQUEST ( 
	   TOKEN VARCHAR(126) NOT NULL,
	   USERNAME VARCHAR(50) NOT NULL,		  
	   CREATION_DATE DATETIME NOT NULL,
	   EXPIRATION_DATE DATETIME NOT NULL,
				
	   PRIMARY KEY(TOKEN)
	  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* PERSISTENT LOGIN (REMEMBER ME) */
CREATE TABLE PERSISTENT_LOGINS(
	   USERNAME VARCHAR(50) NULL,
	   SERIES VARCHAR(64) NULL,
	   TOKEN VARCHAR(64) NULL,
	   LAST_USED TIMESTAMP NULL,		      
	   
	   PRIMARY KEY (SERIES)
	 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* ISSUE HISTORIAL REVISION */		
CREATE TABLE ISSUE_HISTORIAL_REVISION ( 	  
	   ID_ISSUE_HISTORIAL_REVISION BIGINT(20) NOT NULL AUTO_INCREMENT, 	   
	   ID_ISSUE BIGINT(20) NOT NULL, 	   
	   USERNAME VARCHAR(50) NOT NULL,	   
	   HISTORIAL_DATE DATETIME NOT NULL,    	   
	   STATUS VARCHAR(30) NOT NULL, 	    
	   OPERACION VARCHAR(1) NOT NULL,
	   MOTIVO VARCHAR(255) NOT NULL, 	
	   OBSERVACIONES VARCHAR(500) NULL,  
	   CAMPOS_MODIFICADOS VARCHAR(255) NULL, 
	   
	   PRIMARY KEY(ID_ISSUE_HISTORIAL_REVISION),
	   FOREIGN KEY (ID_ISSUE) REFERENCES ISSUE (ID_ISSUE),
	   FOREIGN KEY (USERNAME) REFERENCES USER (USERNAME)
	   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;	


/* ISSUE LICITACION */	
CREATE TABLE ISSUE_LICITACION ( 	  
	   ID_ISSUE_LICITACION BIGINT(20) NOT NULL AUTO_INCREMENT,
	   ID_ISSUE BIGINT(20) NOT NULL, 
	   NRO_LICITACION VARCHAR(20) NOT NULL, 	
	   NRO_EXPEDIENTE VARCHAR(20) NOT NULL, 		  	   	 
       TIPO VARCHAR(20) NOT NULL, 	   
	   OBJETO VARCHAR (255) NOT NULL,	   
	   VALOR_PLIEGO BIGINT(30) NULL,
	   DOCUMENTACION_PLIEGO VARCHAR(255) NULL,	   
	   EMPRESA_CONSTRUCTORA VARCHAR (255) NOT NULL,
	   UNIDAD_EJECUTORA VARCHAR (255) NULL,
	   UNIDAD_FINANCIAMIENTO VARCHAR (255) NULL,
	   REPRESENTANTE_TECNICO VARCHAR (255) NULL,
	   PLAZO_EJECUCION INT(10) NOT NULL,
	   PRESUPUESTO_ADJUDICADO FLOAT (20) NULL,
	   PRESUPUESTO_FINAL FLOAT (20) NULL,
	   FECHA_ESTIMADA_INICIO DATETIME NULL,
	   FECHA_ESTIMADA_FIN DATETIME NULL,
	   FECHA_REAL_INICIO DATETIME NULL,
	   FECHA_REAL_FIN DATETIME NULL,
	   STATUS_OBRA VARCHAR(30) NOT NULL,	  	 
	   
	   PRIMARY KEY(ID_ISSUE_LICITACION),
	   UNIQUE KEY(NRO_LICITACION),
	   FOREIGN KEY (ID_ISSUE) REFERENCES ISSUE (ID_ISSUE)	  
	   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;	


/* COMMENT */			
CREATE TABLE COMMENT ( 	  
	   ID_COMMENT BIGINT(20) NOT NULL AUTO_INCREMENT,    
	   ID_ISSUE BIGINT(20) NOT NULL, 
	   ID_USER VARCHAR(50) NOT NULL,	   
	   COMMENT_DATE DATETIME NULL,    	   
	   COMMENT_MESSAGE VARCHAR(300) NOT NULL,		 
	   FLAG TINYINT(1) default 0,
	   
	   PRIMARY KEY(ID_COMMENT),
	   FOREIGN KEY (ID_ISSUE) REFERENCES ISSUE (ID_ISSUE),
	   FOREIGN KEY (ID_USER) REFERENCES USER (USERNAME)
	   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




		INSERT INTO `user` (`USERNAME`,`PASSWORD`,`SALT`,`EMAIL`,`NEIGHBORHOOD`,`REGISTRATION_DATE`,`LAST_PASSWORD_CHANGE_DATE`,`LAST_LOGIN_DATE`,`CLOSED_ACCOUNT_DATE`,`ENABLED`) 
VALUES ('admin','admin','',NULL,NULL,NULL,NULL,NULL,NULL,1),
('coripel','c7589745dd1841655ac79a8f6fbb8e63b01b1e00','','coripel@gmail.com','Constitución',NULL,NULL,NULL,NULL,1),
('fakeuser','43a3f7f06dc85a1d3249e073c2fe3fa2cfe06cc5','','fakeuser@gmail.com',NULL,NULL,NULL,NULL,NULL,1),
('helloworld','b6fc2132f07b0230ac197d342548c10b1c760ccf','','helloworld@gmail.com',NULL,NULL,NULL,NULL,NULL,1),
('mock','e8a26afff685de0b2e2ae72a6fbb3747a0ed5fe2','','mock@gmail.com',NULL,NULL,NULL,NULL,NULL,1);

INSERT INTO `authority` (`USERNAME`,`AUTHORITY`) 
VALUES ('admin','ROLE_ADMIN'),('coripel','ROLE_USER'),('fakeuser','ROLE_USER'),('helloworld','ROLE_USER'),('mock','ROLE_USER');






	

